spring:
  application:
    name: limpieza-publica-api

  datasource:
    url: jdbc:postgresql://dpg-d33m0vqdbo4c73bb2720-a.oregon-postgres.render.com/segat
    driver-class-name: org.postgresql.Driver
    username: segat_user
    password: fSIpvwutmAsrmoaqoMbuvQEr8V1n9BWa

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  validation:
    enabled: true

logging:
  level:
    com.municipio.limpieza: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
