spring:
  application:
    name: limpieza-publica-api

  datasource:
    url: jdbc:postgresql://localhost:5432/segat  # Conexión a PostgreSQL
    driver-class-name: org.postgresql.Driver  # Para PostgreSQL
    username: postgres  # Usuario de PostgreSQL
    password: 27012007  # Contraseña de PostgreSQL

  h2:
    console:
      enabled: false  # Deshabilita la consola de H2 si no la necesitas

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Dialecto para PostgreSQL
    hibernate:
      ddl-auto: update  # O 'validate' si no quieres que Hibernate modifique la DB
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  validation:
    enabled: true

logging:
  level:
    com.municipio.limpieza: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

web: java -jar target/TrujilloInformado-0.0.1-SNAPSHOT.jar

server:
  port: 8080
  servlet:
    context-path: /
